/**
 * Generates `build/icon.ico` (multi-size) from `build/icon.svg`.
 *
 * The .ico is consumed by electron-builder for the icon of the `.exe`, the
 * installer and the shortcut. It's regenerated by hand —not on every build—
 * because it only changes when the mascot changes; the result is committed as a
 * binary asset.
 *
 * The dependencies do NOT live in the project (they're only for this): install
 * them on the fly before running and remove them afterward:
 *
 *   npm i -D @resvg/resvg-js png-to-ico
 *   node scripts/make-icon.mjs
 *   npm remove @resvg/resvg-js png-to-ico
 *
 * `@resvg/resvg-js` rasterizes the SVG (with gradients) at each size and
 * `png-to-ico` packages them. It's rendered at each size instead of scaling a
 * large one so the small icon (16/32) comes out sharp.
 */
import { Buffer } from 'node:buffer';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';
import pngToIco from 'png-to-ico';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const svg = readFileSync(join(root, 'build', 'icon.svg'), 'utf-8');

const sizes = [256, 128, 64, 48, 32, 16];
const pngs = sizes.map((value) =>
  Buffer.from(new Resvg(svg, { fitTo: { mode: 'width', value } }).render().asPng())
);

const ico = await pngToIco(pngs);
writeFileSync(join(root, 'build', 'icon.ico'), ico);
console.log(`build/icon.ico generado (${sizes.join(', ')} px, ${ico.length} bytes)`);
